### ISSUE TITLE
npm test does not execute any test

### ISSUE THREAD

**Issue by jesusreal** [mgechev/scalable-architecture-demo#5]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I am on my way to create an issue + pull request, and I found out that none of the tests are executed when running ```npm test```.

**Expected behavior**
Tests should run when executing  ```npm test```

**Minimal reproduction of the problem with instructions**
After ```npm i``` and ```npm start```, there are currently some issues because newer versions of_@types/jasmine_ and _typescript_ were installed. I locked the versions to the one specified in package.json and I replaced in _karma.conf.js_ two occurrences of 'dist/dev/assets' with 'dist/dev/app/assets'. Nevertheless, still no test is executed and no error is logged in the console

**What is the motivation / use case for changing the behavior?**
Probably new versions of npm packages getting installed.

**Please tell us about your environment:**
Max OS X 10.11.6, Sublime Text

* **Angular Seed Version:** `17fd226`

* **Node:** `node --version` = v6.9.1

**Comment by mgechev** [comment]
The application showcases only the architecture. There are no any tests and probably the logic added to the core structure provided by the angular seed is already invalid in this repository.

If you're willing to fix the issue feel free but I don't think it's required. The project is not indented to be a starter, instead you can use Angular Seed or Angular CLI.
