### ISSUE TITLE
Error in restful.gateway.ts

### ISSUE THREAD

**Issue by gregbown** [mgechev/scalable-architecture-demo#7]
The app was throwing an error cannot ... length of undefined
Changed code like so and all is well.  Thank you for the great example though!
```
      // const currentText = (command as any).text;
      // const currentTime = new Date((command as any).time);
      const currentText = (command.payload as any).text;
      const currentTime = new Date((command.payload as any).time);
```

**Comment by mgechev** [comment]
Seems like the problem solved by this PR https://github.com/mgechev/scalable-architecture-demo/pull/6/files.
